config/routes.rb
Aula1::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]
  resources :courses

  resources :classrooms, :only => [:index, :create]
  root :to => 'classrooms#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :instructor
  has_many :registrations
  has_many :students, :through => :registrations

  validates_numericality_of :capacity
  validates_presence_of :room, :capacity
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :instructor
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :classrooms
  has_one :contact
  validates_presence_of :name

  def invoice
    classrooms.where("finish_at <= ?", Date.today - 30.days).
      map{|c| c.course.workload}.sum * hourly
  end

end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :student
  belongs_to :classroom
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :registrations
  has_many :classrooms, :through => :registrations
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authorize
    if session[:user_id].nil? 
      session[:last_path] = request.path
      redirect_to new_session_path, :alert => "#{request.path} eh area restrita aos administradores"
    end
  end

  def signed_in?
    !session[:user_id].nil?
  end

  def current_user
    if session[:user_id] then User.find session[:user_id] end
  end
  
  helper_method :signed_in?, :current_user

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :authorize, :only => [:create]

  def index
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.create params[:classroom]
    respond_to do |format|
      if @classroom.valid?
        format.html { redirect_to classrooms_path }
        format.js { render :partial => "list", :content_type => 'text/html' }
      else
        format.html { render :index }
        format.js { render :partial => "form", :content_type => "text/html", :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authorize, :except => [:index, :show]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.find_by_email_and_password(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to session[:last_path], :notice => "Bem vindo!"
    else
      redirect_to new_session_path, :alert => "Email e/ou senha inválidos"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, :notice => "Volte sempre!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for @classroom, :remote => true do |form| %>
  <% if @classroom.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@classroom.errors.count, "erros") %> encontrados:</h2>  
      <ul>
        <% @classroom.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>  
      </ul>  
    </div>  
  <% end %>
  <%= form.label :room %>
  <%= form.text_field :room %>
  <%= form.label :capacity %>
  <%= form.text_field :capacity %>
  <%= form.label :instructor_id %>
  <%= form.select :instructor_id, Instructor.all.map{|i| [i.name, i.id]}, :include_blank => true %>
  <%= form.submit %>
<% end %>

app/views/classrooms/_list.html.erb
<ul>
  <% Classroom.all.each do |classroom| %>
    <li>
      <%= classroom.room %> - 
      <%= classroom.instructor.nil? ? "Sem instrutor" : classroom.instructor.name %>
    </li>
  <% end %>
</ul>

app/views/classrooms/index.html.erb
<h1>Turmas</h1>
<% if signed_in? %>
  <div id = "form">
    <%= render "form" %>
  </div>
<% end %>
<div id = "classrooms">
  <%= render "list" %>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :workload %><br />
    <%= f.number_field :workload %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Workload</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= course.workload %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Workload:</b>
  <%= @course.workload %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fritz</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p>
    <% if signed_in? %>
      Olá <%= current_user.email %> | 
      <%= link_to "Sair", session_path(current_user.id), :method => :delete %>
    <% else %>
      <%= link_to "Entrar", new_session_path %>
    <% end %>
  </p>
  <nav>
    <%= link_to "Cursos", courses_path %>
    <%= link_to "Turmas", classrooms_path %>
  </nav>
  <p style="color:red"><%= flash[:alert] %></p>
  <p style="color:green"><%= flash[:notice] %></p>
<%= yield %>

</body>
</html>